In [1]:
# coding=utf-8
# Copyright 2020 The Google Research Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Training and evaluation"""

import run_lib
from absl import app
from absl import flags
from ml_collections.config_flags import config_flags
import logging
import os
import tensorflow as tf
import jittor as jt

jt.flags.use_cuda = 1
FLAGS = flags.FLAGS

config_flags.DEFINE_config_file(
  "config", None, "Training configuration.", lock_config=True)
flags.DEFINE_string("workdir", None, "Work directory.")
flags.DEFINE_enum("mode", None, ["train", "eval"], "Running mode: train or eval")
flags.DEFINE_string("eval_folder", "eval",
                    "The folder name for storing evaluation results")
flags.mark_flags_as_required(["workdir", "config", "mode"])


def main(argv):
    if FLAGS.mode == "train":
        # Create the working directory (Python version)
        os.makedirs(FLAGS.workdir, exist_ok=True)

        # Set logger so that it outputs to both console and file
        logfile_path = os.path.join(FLAGS.workdir, 'stdout.txt')
        gfile_stream = open(logfile_path, 'w')
        
        handler = logging.StreamHandler(gfile_stream)
        formatter = logging.Formatter('%(levelname)s - %(filename)s - %(asctime)s - %(message)s')
        handler.setFormatter(formatter)
        
        logger = logging.getLogger()
        logger.addHandler(handler)
        logger.setLevel('INFO')

        # Run the training pipeline
        run_lib.train(FLAGS.config, FLAGS.workdir)

    elif FLAGS.mode == "eval":
        # Run the evaluation pipeline
        run_lib.evaluate(FLAGS.config, FLAGS.workdir, FLAGS.eval_folder)

    else:
        raise ValueError(f"Mode {FLAGS.mode} not recognized.")
    
app.run(main)

[i 0921 20:25:36.213657 36 compiler.py:956] Jittor(1.3.9.14) src: /home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/jittor
[i 0921 20:25:36.225294 36 compiler.py:957] g++ at /usr/bin/g++(12.3.0)
[i 0921 20:25:36.226005 36 compiler.py:958] cache_path: /home/a516/.cache/jittor/jt1.3.9/g++12.3.0/py3.8.20/Linux-6.6.87.2xef/13thGenIntelRCx37/4832/default
[i 0921 20:25:36.242665 36 __init__.py:412] Found nvcc(12.8.61) at /usr/local/cuda-12.8/bin/nvcc.
[i 0921 20:25:36.474342 36 __init__.py:412] Found addr2line(2.42) at /usr/bin/addr2line.
[i 0921 20:25:36.573296 36 compiler.py:1013] cuda key:cu12.8.61
[i 0921 20:25:37.214226 36 __init__.py:227] Total mem: 15.43GB, using 5 procs for compiling.
[i 0921 20:25:37.341898 36 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0921 20:25:37.602624 36 init.cc:63] Found cuda archs: [89,]
[w 0921 20:25:39.493675 36 compile_extern.py:203] CUDA related path found in LD_LIBRARY_PATH or PATH, This path may cause jittor found the wrong libs, pleas

Traceback (most recent call last):
  File "/home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/absl/app.py", line 162, in parse_flags_with_usage
    return FLAGS(args)
  File "/home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/absl/flags/_flagvalues.py", line 693, in __call__
    raise _exceptions.UnrecognizedFlagError(
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3552, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-b812846d7c0d>", line 66, in <cell line: 66>
    app.run(main)
  File "/home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/absl/app.py", line 308, in run
    args = _run_init(
  File "/home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/absl/app.py", line 

TypeError: object of type 'NoneType' has no len()

In [11]:
import jittor as jt
import numpy as np
jt.flags.use_cuda = 1
a = jt.Var([1, 2, 3])
a.detach

<function jittor_core.Var.detach>

In [9]:
import torch
b = torch.tensor([1, 2, 3])
b.data

tensor([1, 2, 3])

In [12]:
help(jt.copy)

Help on built-in function copy in module jittor_core.ops:

copy(...)
    Declaration:
    VarHolder* copy(VarHolder* x)



In [7]:
x = jt.array([1, 2, 4])
y = jt.array([3, 4, 5])
x.clamp_(y)

jt.Var([3 4 5], dtype=int32)

In [8]:
from torchvision.utils import make_grid, save_image
help(save_image)

Help on function save_image in module torchvision.utils:

save_image(tensor: Union[torch.Tensor, List[torch.Tensor]], fp: Union[str, pathlib.Path, BinaryIO], format: Union[str, NoneType] = None, **kwargs) -> None
    Save a given Tensor into an image file.
    
    Args:
        tensor (Tensor or list): Image to be saved. If given a mini-batch tensor,
            saves the tensor as a grid of images by calling ``make_grid``.
        fp (string or file object): A filename or a file object
        format(Optional):  If omitted, the format to use is determined from the filename extension.
            If a file object was used instead of a filename, this parameter should always be used.
        **kwargs: Other arguments are documented in ``make_grid``.



In [23]:
import numpy as np
x = jt.zeros((3, 138, 70,))
print(x.shape)
import torch
from PIL import Image
y = torch.zeros((3, 138, 70,))
print(y.shape)
x = x.permute(1,2,0).numpy()
y = y.permute(1,2,0).numpy()
im = Image.fromarray(y).numpy()
am = Image.fromarray(x).numpy()

[3,138,70,]
torch.Size([3, 138, 70])



Compiling Operators(1/1) used:  2.5s eta:    0s 


TypeError: Cannot handle this data type: (1, 1, 3), <f4

In [32]:
import jittor as jt
import numpy as np
a = jt.Var([1, 2, 3]).to("cpu", jt.uint8).numpy()
a

array([1, 2, 3], dtype=int32)

In [33]:
# 使用torch代码对照
import torch
import numpy as np
b = torch.Tensor([1, 2, 3]).to("cpu", torch.uint8).numpy()
b

array([1, 2, 3], dtype=uint8)