In [3]:
import jittor as jt

# 定义两个张量
a = jt.array([[1, 2], [3, 4]])
b = jt.array([[5, 6], [7, 8]])
c = jt.pow(a, 2)
c

jt.Var([[ 1  4]
        [ 9 16]], dtype=int32)

In [26]:
from numpy import dtype


help(jt.Var.shape)
print(a.shape)

Help on getset descriptor jittor.jittor_core.Var.shape:

shape
    Document:
    * 
         * return the shape of the Var.
         
    Declaration:
    inline NanoVector shape()

[2,2,]


In [27]:
c = jt.arange(24).reshape(6, 4)
c

RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.numpy)).

Types of your inputs are:
 self	= Var,
 args	= (),

The function declarations are:
 ArrayArgs fetch_sync()

Failed reason:[f 0831 17:35:15.687319 44 parallel_compiler.cc:331] Error happend during compilation:
 [Error] source file location:/home/a516/.cache/jittor/jt1.3.9/g++12.3.0/py3.8.20/Linux-6.6.87.2xef/13thGenIntelRCx37/4832/default/cu12.8.61/jit/code__IN_SIZE_2__in0_dim_1__in0_type_int32__in1_dim_1__in1_type_int32__OUT_SIZE_2__out0_di___hash_fdebb71a9f996516_op.cc
Compile operator(0/2)failed:Op(1066:0:2:2:i2:o2:s0:g1,code->...)

Reason: [f 0831 17:35:12.596987 64:C0 op_compiler.cc:719] [f 0831 17:35:12.596982 64:C0 op_compiler.cc:719] [f 0831 17:35:12.596974 64:C0 op_compiler.cc:719] [f 0831 17:35:12.596951 64:C0 op_compiler.cc:687] Check failed macros.at(dim)(1) == S(args.size())(2) out dimension not matched
Jit compiler error:
                            @out(i, j) = @in0(i, j) + @in1(i, j);
Jit compiler error:
@HEADER
Jit compiler error:
#ifndef JIT


In [28]:
crop = jt.minimum(c.shape[0], c.shape[1])
h, w = c.shape[0], c.shape[1]
crop, h, w


Compiling Operators(1/2) used: 2.31s eta: 2.31s 2/2) used: 3.32s eta:    0s 


(jt.Var([4], dtype=int32), 6, 4)

In [29]:
c = c[(h - crop) // 2:(h + crop) // 2,
          (w - crop) // 2:(w + crop) // 2]
c.unsqueeze(0)


Compiling Operators(1/3) used: 2.32s eta: 4.63s 3/3) used: 3.33s eta:    0s 

Compiling Operators(1/1) used: 2.53s eta:    0s 

Compiling Operators(2/2) used: 2.32s eta:    0s 


jt.Var([[[ 4  5  6  7]
         [ 8  9 10 11]
         [12 13 14 15]
         [16 17 18 19]]], dtype=int32)

In [30]:
C = jt.randint(0, 256, (1, 3, 28, 28), dtype=jt.uint8)
C


Compiling Operators(1/1) used: 2.53s eta:    0s 


jt.Var([[[[160 195  89 ... 226  12   6]
          [ 21  28  58 ...  68  93 188]
          [191 190  21 ... 242 144 175]
          ...
          [198 169 171 ...  82  99 192]
          [179 249 237 ...  22 116 175]
          [218 144 155 ... 227 221  62]]
       
         [[224  43  59 ... 191 204 147]
          [218  90 141 ...  18 152  73]
          [ 11   2  10 ...  27 194 167]
          ...
          [217 192 241 ... 174 176 130]
          [  7 133  46 ...  90 109 186]
          [219 218 225 ...  87 232 113]]
       
         [[ 25 186 172 ...  63 253 235]
          [166 219  14 ... 199  70 151]
          [ 36 232 232 ... 234 193  69]
          ...
          [255 124  37 ... 180 133 150]
          [ 10 229 208 ... 253 238  33]
          [ 34 166 186 ...  73 246 184]]]], dtype=uint8)

In [31]:
d = jt.randint(0, 2, (1, 3, 3))
d = d.unsqueeze(0)

In [32]:
import jittor.transform as jtf
import jittor.nn as nn
def crop_resize(image, resolution):
  """Crop and resize an image to the given resolution."""
  crop = jt.minimum(image.shape[2], image.shape[3])
  h, w = image.shape[2], image.shape[3]
  image = image[(h - crop) // 2:(h + crop) // 2,
          (w - crop) // 2:(w + crop) // 2]
  
  image = nn.resize(
    image,
    size=(resolution, resolution),
    mode='bicubic'
  )
  
  return jt.cast(image, jt.uint8)
crop_resize(d, 5)


Compiling Operators(1/1) used: 2.64s eta:    0s 

Compiling Operators(1/2) used: 2.31s eta: 2.31s 2/2) used: 4.56s eta:    0s 


jt.Var([[[[1 1 1 0 0]
          [0 1 0 0 0]
          [1 1 1 0 0]
          [0 1 0 0 0]
          [1 1 1 0 0]]]], dtype=uint8)

In [33]:
len(C.shape)

4

In [34]:
e = jt.Var([1,2,3.3,4])
e = jt.round(e, dtype=jt.int32)
e = e.cast(jt.int32)
e


Compiling Operators(1/1) used: 2.53s eta:    0s 


jt.Var([1 2 3 4], dtype=int32)

In [35]:
def resize_small(image, resolution):
  """Shrink an image to the given resolution. **It only receives 4D tensor.**"""
  h, w = image.shape[2], image.shape[3]
  ratio = resolution / min(h, w)
  h = jt.round(h * ratio).cast(jt.int32).item()
  w = jt.round(w * ratio).cast(jt.int32).item()
  return nn.resize(image, (h, w))
resize_small(C, 2)


Compiling Operators(1/3) used: 2.31s eta: 4.63s 3/3) used: 3.32s eta:    0s 

Compiling Operators(1/1) used: 2.57s eta:    0s 


jt.Var([[[[160 215]
          [217 251]]
       
         [[224 154]
          [157 168]]
       
         [[ 25 221]
          [215 208]]]], dtype=uint8)

In [36]:
help(jt.transform.crop)

Help on function crop in module jittor.transform:

crop(img, top, left, height, width)
    Function for cropping image.
    
    Args::
    
        [in] img(Image.Image): Input image.
        [in] top(int): the top boundary of the cropping box.
        [in] left(int): the left boundary of the cropping box.
        [in] height(int): height of the cropping box.
        [in] width(int): width of the cropping box.
    
    Example::
        
        img = Image.open(...)
        img_ = transform.crop(img, 10, 10, 100, 100)



In [37]:
jt.get_device_count()

1

In [1]:
from jittor import Function
jt.flags.use_cuda = 1

class Func(Function):
    def execute(self, a, b):
        self.save_vars = a, b
        return jt.code(a.shape, a.dtype, [a,b],
            cuda_src='''
                __global__ static void kernel1(@ARGS_DEF) {
                    @PRECALC
                    for (int i=blockIdx.x; i<in0_shape0; i+=gridDim.x)
                    for (int j=threadIdx.x; j<in0_shape1; j+=blockDim.x)
                        @out(i,j) = @in0(i,j)*@in1(i,j);
                }
                kernel1<<<32, 32>>>(@ARGS);
            ''')

    def grad(self, grad):
        a, b = self.save_vars
        return jt.code([a.shape, b.shape], [a.dtype, b.dtype], [a, b, grad],
            cuda_src='''
                __global__ static void kernel2(@ARGS_DEF) {
                    @PRECALC
                    for (int i=blockIdx.x; i<in0_shape0; i+=gridDim.x)
                    for (int j=threadIdx.x; j<in0_shape1; j+=blockDim.x) {
                        @out0(i,j) = @in2(i,j)*@in1(i,j);
                        @out1(i,j) = @in2(i,j)*@in0(i,j);
                    }
                }
                kernel2<<<32, 32>>>(@ARGS);
            ''')
        
a = jt.random((100,100))
b = jt.random((100,100))
func = Func()
c = func(a,b)
print(c)
print(jt.grad(c, [a, b]))

[i 0831 19:58:25.110016 68 compiler.py:956] Jittor(1.3.9.14) src: /home/a516/anaconda3/envs/Jittor/lib/python3.8/site-packages/jittor
[i 0831 19:58:25.114661 68 compiler.py:957] g++ at /usr/bin/g++(12.3.0)
[i 0831 19:58:25.115197 68 compiler.py:958] cache_path: /home/a516/.cache/jittor/jt1.3.9/g++12.3.0/py3.8.20/Linux-6.6.87.2xef/13thGenIntelRCx37/4832/default
[i 0831 19:58:25.123968 68 __init__.py:412] Found nvcc(12.8.61) at /usr/local/cuda-12.8/bin/nvcc.
[i 0831 19:58:25.246535 68 __init__.py:412] Found addr2line(2.42) at /usr/bin/addr2line.
[i 0831 19:58:25.308949 68 compiler.py:1013] cuda key:cu12.8.61
[i 0831 19:58:25.764482 68 __init__.py:227] Total mem: 15.43GB, using 5 procs for compiling.
[i 0831 19:58:25.896417 68 jit_compiler.cc:28] Load cc_path: /usr/bin/g++
[i 0831 19:58:26.150737 68 init.cc:63] Found cuda archs: [89,]
[w 0831 19:58:26.484639 68 compile_extern.py:203] CUDA related path found in LD_LIBRARY_PATH or PATH, This path may cause jittor found the wrong libs, pleas

NameError: name 'jt' is not defined

In [49]:
import jittor as jt

def add_same_shape(a, b):
    assert a.shape == b.shape, "张量形状必须完全相同"
    return jt.code(
        [a.shape, b.shape],        # 输入形状
        [a.dtype, b.dtype],                 # 输出类型（和输入一致）
        [a, b],                    # 输入张量
        cuda_src='''
        __global__ void kernel_add(@ARGS_DEF) {
            @PRECALC
            int N = in0_num; 
            int idx = threadIdx.x + blockIdx.x * blockDim.x;
            int stride = blockDim.x * gridDim.x;

            for (int i = idx; i < N; i += stride) {
                @out_flat[i] = @in0_flat[i] + @in1_flat[i];
            }
        }

        
        int threads = 256;
        int blocks = (in0_num + threads - 1) / threads;
        kernel_add<<<blocks, threads>>>(@ARGS);
        '''
    )


In [50]:
jt.flags.use_cuda = 1
a = jt.Var([1, 2])
b = jt.Var([3, 4])
add_same_shape(a, b)

RuntimeError: Wrong inputs arguments, Please refer to examples(help(jt.numpy)).

Types of your inputs are:
 self	= Var,
 args	= (),

The function declarations are:
 ArrayArgs fetch_sync()

Failed reason:[f 0831 17:38:27.893350 44 parallel_compiler.cc:331] Error happend during compilation:
 [Error] source file location:/home/a516/.cache/jittor/jt1.3.9/g++12.3.0/py3.8.20/Linux-6.6.87.2xef/13thGenIntelRCx37/4832/default/cu12.8.61/jit/code__IN_SIZE_2__in0_dim_1__in0_type_int32__in1_dim_1__in1_type_int32__OUT_SIZE_2__out0_di___hash_d3924fc96af2ce9d_op.cc
Compile operator(1/2)failed:Op(2149:0:2:2:i2:o2:s0:g1,code->...)

Reason: [f 0831 17:38:27.893318 60:C1 op_compiler.cc:719] [f 0831 17:38:27.893314 60:C1 op_compiler.cc:719] [f 0831 17:38:27.893306 60:C1 op_compiler.cc:719] [f 0831 17:38:27.893291 60:C1 op_compiler.cc:702] Check failed: iter!=defs.end()  Something wrong... Could you please report this issue?
 Jit var  out_flat  not found.
Jit compiler error:
                @out_flat[i] = @in0_flat[i] + @in1_flat[i];
Jit compiler error:
@HEADER
Jit compiler error:
#ifndef JIT
